import "../globals.css";
import type { Metadata } from "next";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import Section1 from "@/components/shared/Section1";
import Section2 from "@/components/shared/Section2";
import Section3 from "@/components/shared/Section3";
import ThemeRegistry from "@/components/ThemeRegistry/ThemeRegistry";

export const metadata: Metadata = {
  title: "student.io",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <Navbar />

          <Section1 />
          <Section2 />
          <Section3 />
          <Footer />
        </ThemeRegistry>
      </body>
    </html>
  );
}
